config/routes.rb
Rails.application.routes.draw do

  resources :feeds
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  root 'tops#index'

  resources :coments do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :user_id,{presence: true}
  validates :content,
  presence: true,
  length: {maximum: 140}

  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :coment

  validates :user_id,{presence: true}
  validates :coment_id,{presence: true}
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :coments,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_coments,through: :favorites,source: :coment

  validates :name,presence: true,length: { maximum: 30 }
  validates :email,presence: true,length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }
  has_secure_password
  validates :password,presence: true,length: {minimum:6 }

  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  before_action :set_coment, only: [:show, :edit, :update, :destroy]

  # GET /coments
  def index
    @coments = Coment.all.order(created_at: :desc)
  end

  # GET /coments/1
  def show
    @coment = Coment.find_by(id: params[:id])
    @user = User.find_by(id: @coment.user_id)
    @favorite = current_user.favorites.find_by(coment_id: @coment.id)
  end

  # GET /coments/new
  def new
    if params[:back]
      @coment = Coment.new(coment_params)
      if params[:cache][:image] != ""
        @coment.image.retrieve_from_cache! params[:cache][:image]
      end
    else
      @coment = Coment.new
    end
  end

  # GET /coments/1/edit
  def edit
  end

  # POST /coments
  def create
    @coment = Coment.new(coment_params)
    @coment.user_id = current_user.id

    if params[:cache][:image] != ""
      @coment.image.retrieve_from_cache! params[:cache][:image]
      @coment.save!
    end

    if @coment.save
      ComentMailer.coment_mail(@coment).deliver
      redirect_to new_coment_path,
      notice: 'Coment was successfully created!'
    else
      render 'new'
    end
  end

  # PATCH/PUT /coments/1
  def update
    if @coment.update(coment_params)
      redirect_to coments_path,
      notice: 'Coment was successfully updated!'
    else
      render 'edit'
    end
  end

  # DELETE /coments/1
  def destroy
    if @coment.destroy
      redirect_to coments_path,
      notice: 'Coment was successfully destroyed!'
    end
  end

  def confirm
    @coment = Coment.new(coment_params)
    @coment.user_id = current_user.id
    render :new if @coment.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coment
      @coment = Coment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coment_params
      params.require(:coment).permit(:content,:image,:image_cache)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = current_user.favorites.create(coment_id: params[:coment_id])
    redirect_to coments_url, notice: "#{@favorite.coment.user.name}さんのComent!>favorite!!"
  end

  def destroy
    @favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to coments_url, notice: "#{@favorite.coment.user.name}さんのComent!>remove favorite."
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.image.retrieve_from_cache! params[:cache][:image]
    @feed.save!
    if @feed.save
      redirect_to @feed, notice: 'Feed was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.'
    else
      render 'edit'
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:image,:image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @favorites_coments = @user.favorite_coments
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation,:icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_coments_path
    elsif action_name == 'edit'
      coment_path
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coments/_form.html.erb
<%= form_with(model: @coment, local: true, url: choose_new_or_edit) do |form| %>
  <% if @coment.errors.any? %>
    <div class="form-error">
      <h3><%= pluralize(coment.errors.count, "error") %> prohibited this coment from being saved:</h3>
      <ul>
      <% @coment.errors.full_messages.each do |message| %>
        <h3><%= message %></h3>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-body">
    <%= form.label :coment %>
    <div class="post-coment">
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image, id: :feed_image %>
      <%= form.hidden_field :image_cache %>
    </div>

    <% unless new_coment_path %>
      <div class="post-time">
        <%= coment.created_at.strftime('%Y/%m/%d %H:%M')%>
      </div>
    <% end %>
    <%= form.submit %>
  </div>
<% end %>
<div class="page-back">
  <%= link_to 'Back', coments_path %>
</div>

app/views/coments/confirm.erb
<div class="main posts-new">
  <div class="page-logo">
    <h2>Coment OK?</h2>
  </div>
  
  <div class="container">
    <div class="form-body">
      <%= form_with(model: @coment, url: coments_path, local: true) do |form| %>
        <%= form.hidden_field :content %>
        <p class="post-coment">
            <%= @coment.content %>
          </p>
        <%= form.submit  "Coment!" %>
      <% end %>
      <%= form_with(model: @coment, url: new_coment_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :content %>
        <%= form.submit "Back",name: 'back' %>
      <% end %>
    </div>
  </div>
</div>

app/views/coments/confirm.html.erb
<div class="main posts-new">
  <div class="page-logo">
    <h2>Coment OK?</h2>
  </div>

  <div class="container">
    <div class="form-body">
      <%= form_with(model: @coment, url: coments_path, local: true) do |form| %>
        <%= form.hidden_field :content %>
        <p class="post-coment">
          <%= @coment.content %>
        </p>
        <div class="field">
          <%= image_tag(@coment.image) if @coment.image.url %>
          <%= form.hidden_field :image %>
          <%= hidden_field_tag :"cache[image]",@coment.image.cache_name %>
        </div>
        <%= form.submit  "Coment!" %>
      <% end %>

      <%= form_with(model: @coment, url: new_coment_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image %>
        <%= hidden_field_tag :"cache[image]",@coment.image.cache_name %>
        <%= form.submit "Back",name: 'back' %>
      <% end %>
    </div>
  </div>
</div>

app/views/coments/edit.html.erb
<div class="main posts-new">
  <div class="page-logo">
    <h1>Editing Coment</h1>
  </div>
  <div class="container">
    <%= render 'form', coment: @coment %>
  </div>
</div>

app/views/coments/index.html.erb
<div class="main main-table">
  <div class="page-logo">
    <h2>･:*+.All Coment.:+*</h2>
  </div>

  <div class="posts-index">
    <div class="row row-eq-height container">
      <% @coments.each do |coment| %>
        <div class="col-xs-12 col-md-6 posts-show-item">
          <div class="post-icon">
            <%= image_tag coment.user.icon %>
          </div>
          <div class="post-user-name">
            ＜<%= coment.user.name %>
          </div>
          <p class="post-coment">
            <%= coment.content %>
          </p>
          <div class="post-image">
            <%= image_tag coment.image %>
          </div>
          <div class="post-time">
            <%= coment.created_at.strftime('%Y/%m/%d %H:%M')%>
          </div>
          <div class="post-menus">
            <% if coment.user_id == current_user.id %>
              <%= link_to 'edit', edit_coment_path(coment.id),data: {confirm: '本当に編集していいですか？'},class: 'btn btn-info' %>
              <%= link_to 'delete', coment_path(coment.id), method: :delete,data: {confirm: '本当に削除していいですか？'},class: 'btn btn-warning' %>
            <% end %>
            <%= link_to 'show', coment_path(coment.id),class: 'btn btn-info' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/coments/new.html.erb
<div class="main posts-new">
  <div class="page-logo">
    <h1>New coments</h1>
  </div>
  <div class="container">
    <%= render 'form', coment: @coment %>
  </div>
</div>

app/views/coments/show.html.erb
<div class="main posts-show">
  <p id="notice">
    <%= notice %>
  </p>
  <div class="page-logo">
    <h1>Show Coment</h1>
  </div>
  <div class="container">
    <div class="posts-show-item">
      <div class="post-icon">
        <%= image_tag @coment.user.icon %>
      </div>
      <div class="post-user-name">
        ＜<%= @user.name %>
      </div>
      <p class="post-coment">
        <%= @coment.content %>
      </p>
      <div class="post-image">
        <%= image_tag @coment.image %>
      </div>
      <div class="post-time">
        <%= @coment.created_at.strftime('%Y/%m/%d %H:%M')%>
      </div>
      <div class="post-menus">
        <% unless @coment.user_id == current_user.id %>
          <% if @favorite.present? %>
            <%= link_to 'favorite?', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-warning' %>
          <% else %>
            <%= link_to 'favorite!', favorites_path(coment_id: @coment.id), method: :post, class: 'btn btn-info' %>
          <% end %>
        <% end %>
        <% if @coment.user_id == current_user.id %>
          <%= link_to 'Edit', edit_coment_path(@coment) ,class: 'btn btn-info'%>
        <% end %>
        <%= link_to 'Back', coments_path ,class: 'btn btn-warning'%>
      </div>
    </div>
  </div>
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url:confirm_feeds_path) do |form| %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image.url %>
    <%= form.file_field :image, id: :feed_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= image_tag(@feed.image) %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Coments!</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><h1>Coments!</h1>

            </a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li><%= link_to "Profile", user_path(current_user.id) %></li>
                <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
                <li><%= link_to 'All Coment', coments_path %></li>
                <li><%= link_to 'New Coment', new_coment_path %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Login", new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if notice %>
      <div class = "flash">
        <%= notice %>
      </div>
    <% end %>

    <% flash.each do |key, value| %>
      <div class="flash">
        <%= content_tag(:div, value, class: "#{key}") %>
      </div>
    <% end %>

    <%= yield %>

    <footer>
      <p>*+:｡.｡create_by_remixk13｡.｡:+*</p>
      <p>It becomes portfolio. Thank you for viewing！</p>
    </footer>

  </body>
</html>

app/views/tops/index.html.erb
<div class="main main-table">
  <div class="page-top">
    <div class="page-logo">
      <h2>･:*+.About Coments!.:+*</h2>
    </div>
    <div class="top-contents">
      <p>簡単に思ったことや感じたことを記録出来る</p>
      <p>ブログよりも気軽に利用出来るコメント機能です。</p>

      <div class="top-menus">
        <h3>Start!</h3>
        <% if logged_in? %>
        <%= link_to "Logout", session_path(current_user.id),class: 'btn btn-info', method: :delete %>
        <% else %>
        <%= link_to "SignUp", new_user_path,class: 'btn btn-info' %>
        <span>or</span>
        <%= link_to "Login", new_session_path,class: 'btn btn-warning' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="page-logo">
    <h1>Sign Up!</h1>
  </div>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="container">
    <div class="form-body">
      <div class="user_name">
        <%= f.label :name %>
      </div>
      <div class="user_forms">
        <%= f.text_field :name %>
      </div>
      <%= f.label :icon %>
      <%= f.file_field :icon,id: :user_icon %>
      <%= f.hidden_field :icon_cache %>
      <div class="user_email">
        <%= f.label :email %>
      </div>
      <div class="user_forms">
        <%= f.email_field :email %>
      </div>

      <div class="user_pass">
        <%= f.label :password %>
      </div>
      <div class="user_forms">
        <%= f.password_field :password %>
        ※６文字以上
      </div>

      <div class="user_pass_confirm">
        <%= f.label :password！ %>
      </div>
      <div class="user_forms">
        <%= f.password_field :password_confirmation %>
        ※確認の為上記パスワード再入力
      </div>
      <%= f.submit "Create my account" %>
    </div>
   </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="page-logo">
    <h1>Login User : <%= @user.name %></h1>
  </div>

  <div class="container">
    <div class="user">
      <div class="icon">
        <%= image_tag @user.icon %>
      </div>
      <div>
        <p>Name : <%= @user.name %></p>
      </div>
      <div>
        <p>Email : <%= @user.email %></p>
      </div>
    </div>

    <div class="favorites">
      <h3>Favorites!</h3>
      <div class="fav-list-item">
        <% @favorites_coments.each do |favorites_coment| %>
        <div class="fav-user-name">
          [<%= favorites_coment.user.name %>]
        </div>
        <p class="fav-coment">
          ><%= favorites_coment.content %>
          <%= link_to "show", coment_path(favorites_coment.id),class: 'btn btn-info' %>
        </p>
      <% end %>
      </div>
    </div>
  </div>
</div>